"""Add generation_jobs_logs table

Revision ID: 1fce86ab1ca5
Revises: 40341b22ea01
Create Date: 2026-04-06 18:27:59.020703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fce86ab1ca5'
down_revision: Union[str, Sequence[str], None] = '40341b22ea01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('logger', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_logs_id'), 'generation_jobs_logs', ['id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_logs_job_id'), 'generation_jobs_logs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_logs_job_id'), table_name='generation_jobs_logs')
    op.drop_index(op.f('ix_generation_jobs_logs_id'), table_name='generation_jobs_logs')
    op.drop_table('generation_jobs_logs')
    # ### end Alembic commands ###
