"""add_indices

Revision ID: 2717c8d24cad
Revises: 969705326df4
Create Date: 2026-04-15 15:32:43.348073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2717c8d24cad'
down_revision: Union[str, Sequence[str], None] = '969705326df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documentation_revisions_endpoint_id'), 'documentation_revisions', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_documentation_revisions_submitted_by'), 'documentation_revisions', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_documentation_revisions_team_id'), 'documentation_revisions', ['team_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_project_name'), 'generation_jobs', ['project_name'], unique=False)
    op.create_index(op.f('ix_generation_jobs_submitted_by'), 'generation_jobs', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_generation_jobs_team_id'), 'generation_jobs', ['team_id'], unique=False)
    op.create_index(op.f('ix_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_team_id'), 'prompt_templates', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_actor_user_id'), 'team_invitations', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_invitee_user_id'), 'team_invitations', ['invitee_user_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_team_id'), 'team_invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_invitations_team_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_invitee_user_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_actor_user_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_prompt_templates_team_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_projects_team_id'), table_name='projects')
    op.drop_index(op.f('ix_generation_jobs_team_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_submitted_by'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_project_name'), table_name='generation_jobs')
    op.drop_index(op.f('ix_documentation_revisions_team_id'), table_name='documentation_revisions')
    op.drop_index(op.f('ix_documentation_revisions_submitted_by'), table_name='documentation_revisions')
    op.drop_index(op.f('ix_documentation_revisions_endpoint_id'), table_name='documentation_revisions')
    # ### end Alembic commands ###
