"""add api_dir to generation_jobs

Revision ID: 40341b22ea01
Revises: c7e1f2a3b4d5
Create Date: 2026-04-05 23:03:52.237706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40341b22ea01'
down_revision: Union[str, Sequence[str], None] = 'c7e1f2a3b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('api_dir', sa.String(), nullable=True))
    op.drop_constraint(op.f('team_members_user_id_fkey'), 'team_members', type_='foreignkey')
    op.drop_constraint(op.f('team_members_team_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_teams_slug'), 'teams', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_teams_slug'), 'teams', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_team_id_fkey'), 'team_members', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('team_members_user_id_fkey'), 'team_members', 'users', ['user_id'], ['id'])
    op.drop_column('generation_jobs', 'api_dir')
    # ### end Alembic commands ###
