"""Phase 5 documentation revisions

Revision ID: 8f596fa12dd3
Revises: 9e292fe203c0
Create Date: 2026-04-04 22:06:45.681066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f596fa12dd3'
down_revision: Union[str, Sequence[str], None] = '9e292fe203c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentation_revisions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=255), nullable=False),
    sa.Column('endpoint_id', sa.String(length=255), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('proposed_content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='revisionstatus'), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentation_revisions')
    # ### end Alembic commands ###
